import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/app/components/Slidebar/Sidebar";
import GlobalStylesProvider from "@/app/providers/GlobalStylesProvider";
import ContextProvider from "@/app/providers/ContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ContextProvider>
          <GlobalStylesProvider>
              <Sidebar/>
              {children}
          </GlobalStylesProvider>
      </ContextProvider>
      </body>
    </html>
  );
}
